[package]
name = "lattice-css-build"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.57", features = ["derive"] }
lightningcss = { version = "1.0.0-alpha.70", default-features = false, features = ["bundler"] }
